---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 30m
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher
      interval: 12h
  values:
    hostname: rancher.cluster.io
    ingress:
      ingressClassName: nginx
